FROM registry.access.redhat.com/ubi8/openjdk-21:1.20
COPY target/lib/ /deployments/lib/
COPY target/*-runner.jar /deployments/spring-run.jar

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dspring.http.host=0.0.0.0"
ENV JAVA_APP_JAR="/deployments/spring-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
