server:
  port: 8091
  error:
    include-stacktrace: never
spring:
  config:
    import:
      - classpath:/doc.yml
      - classpath:/management.yml
      - classpath:/logging.yml
      - classpath:/security.yml
  application:
    name: '@project.name@'
  devtools:
    restart:
      enabled: false
  security:
    user:
      name: admin
      password: admin
      roles: ${ROLES}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60000
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        corsConfigurations:
              '[/**]':
                allow-credentials: true
                allowed-origins: http://frontend.local
                allowed-methods: GET, POST, PUT, DELETE, OPTIONS
                allowed-headers: '*'
      routes:
        - id: products
          uri: ${URL_PRODUCT:http://localhost:8080}
          predicates:
            - Path=/api/products/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: GET, POST, PUT, DELETE
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

