FROM oven/bun:latest AS build
WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

COPY . .

ENV VITE_API_URL=http://api-gateway.local/api/products
RUN bun run build

FROM nginx:latest AS deploy
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist .
COPY ./DevOps/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
